import profile from "../assets/images/profile.png";
import thumbnail from "../assets/images/thumbnail.png";
import cards from "../assets/images/cards.png";
import path from "../assets/images/path.png";
import logo from "../assets/images/logo.png";
import logoSmall from "../assets/images/logo-small.png";
import empty from "../assets/images/empty.png";
import verified from "../assets/images/verified.png";
import logovertical from "../assets/images/logo-vertical.png";
import logoverticalshort from "../assets/images/logo-vertical-short.png";
import logoname from "../assets/images/logo-name.png";
import logoname2 from "../assets/images/logo-name-2.png";
import carMarker from "../assets/images/car-marker.png";
import logoverticalshortblack from "../assets/images/logo-vertical-short-black.png";
import google from "../assets/images/google.png";
import evchargingstation from "../assets/images/ev-charging-station.jpg";
import evchargerheader from "../assets/images/charger-header.png";
import electraFindQR from "../assets/images/ElectraFindQR.png";
import mechanic1 from "../assets/images/mechanic1.jpeg";
import mechanic2 from "../assets/images/mechanic2.jpeg";
import mechanic3 from "../assets/images/mechanic3.jpeg";
import mechanic4 from "../assets/images/mechanic4.jpeg";
import mechanic5 from "../assets/images/mechanic5.jpeg";
import mechanic6 from "../assets/images/mechanic6.jpeg";
import mechanic7 from "../assets/images/mechanic7.jpeg";
import servicestation1 from "../assets/images/servicestation1.jpeg";
import servicestation2 from "../assets/images/servicestation2.jpeg";
import servicestation3 from "../assets/images/servicestation3.jpeg";
import servicestation4 from "../assets/images/servicestation4.jpeg";
import servicestation5 from "../assets/images/servicestation5.jpeg";
import servicestation6 from "../assets/images/servicestation6.jpeg";
import carService from "../assets/images/car-service.png";
import carImage from "../assets/images/tesla-voiture.jpg";
import serviceImage from "../assets/images/service-station.jpg";
import order from "../assets/images/order.png";
import ccstype1 from "../assets/images/ccstype1.png";
import ccstype2 from "../assets/images/ccstype2.png";
import chademo from "../assets/images/chademo.png";
import type1 from "../assets/images/type1.png";
import type2 from "../assets/images/type2.png";



export default { profile, google, order, ccstype1, ccstype2, chademo, type1, type2, evchargingstation,serviceImage, carImage, carService, electraFindQR, evchargerheader, thumbnail, cards, path, logo, logoSmall, empty, verified, logovertical, logoverticalshort, logoname, logoname2, carMarker, logoverticalshortblack, mechanic1, mechanic2, mechanic3, mechanic4, mechanic5, mechanic6, mechanic7, servicestation1, servicestation2, servicestation3, servicestation4, servicestation5, servicestation6};
